---
- hosts: dockerhost
  become: no
  tasks:
    - name: Remove container if any
      docker_container:
        state: absent
        name: sowtracker

    - name: Remove Image if any
      docker_image:
        state: absent
        name: 18.206.95.238:8085/sowtracker:1.3

    - name: Log into private registry and force re-authorization
      docker_login:
        registry: 'http://18.206.95.238:8085'
        username: "admin"
        password: "nexusadmin"

    - name: Ensure a container is running
      docker_container:
        name: sowtracker
        state: started
        image: 18.206.95.238:8085/sowtracker:1.3
        pull: true
        ports:
          - "8080:80"
