---
- hosts: dockerhost
  become: no
  tasks:
    - name: Remove container if any
      docker_container:
        state: absent
        name: sowtracker

    - name: Remove Image if any
      docker_image:
        state: absent
        name: 3.84.132.212:8085/sowtracker:1.2

    - name: Log into private registry and force re-authorization
      docker_login:
        registry: 'http://3.84.132.212:8085'
        username: "admin"
        password: "nexusadmin"

    - name: Ensure a container is running
      docker_container:
        name: sowtracker
        state: started
        image: 3.84.132.212:8085/sowtracker:1.2
        pull: true
        ports:
          - "8080:80"
