---
- hosts: dockerhost
  become: no
  vars_files:
    - vars.yml

  tasks:
    - name: Remove container if any
      docker_container:
        state: absent
        name: sowtracker

    - name: Remove Image if any
      docker_image:
        state: absent
        name: "{{ dockerimage }}"

    - name: Log into private registry and force re-authorization
      docker_login:
        registry: 'http://{{prv_reg_add}}'
        username: "{{nexus_user}}"
        password: "{{nexus_secret}}"

    - name: Ensure a container is running
      docker_container:
        name: sowtracker
        state: started
        image: "{{ dockerimage }}"
        pull: true
        ports:
          - "8080:80"
